#include "TROOT.h"
#include "TFile.h"
#include "TLegend.h"
#include "TCanvas.h"
#include "TRandom.h"
#include "TH1D.h"
#include "TStyle.h"

void test_ZllNormalization(){
  gROOT->SetStyle("Plain");
  gStyle->SetOptStat(0);
  TFile *_file0 = TFile::Open("zyield.root");
  _file0->cd(); 
  TH1D* ZmmMass_MC	 = (TH1D*) gROOT->FindObject("ZmmMass_MC");
  TH1D* ZmmMass_MC_BB	 = (TH1D*) gROOT->FindObject("ZmmMass_MC_BB");
  TH1D* ZmmMass_MC_EE	 = (TH1D*) gROOT->FindObject("ZmmMass_MC_EE");
  TH1D* ZmmMass_MC_EB	 = (TH1D*) gROOT->FindObject("ZmmMass_MC_EB");
  TH1D* ZeeMass_MC	 = (TH1D*) gROOT->FindObject("ZeeMass_MC");
  TH1D* ZeeMass_MC_BB	 = (TH1D*) gROOT->FindObject("ZeeMass_MC_BB");
  TH1D* ZeeMass_MC_EE	 = (TH1D*) gROOT->FindObject("ZeeMass_MC_EE");
  TH1D* ZeeMass_MC_EB	 = (TH1D*) gROOT->FindObject("ZeeMass_MC_EB");
  TH1D* ZmmMass_DA	 = (TH1D*) gROOT->FindObject("ZmmMass_DA");
  TH1D* ZmmMass_DA_BB	 = (TH1D*) gROOT->FindObject("ZmmMass_DA_BB");
  TH1D* ZmmMass_DA_EE	 = (TH1D*) gROOT->FindObject("ZmmMass_DA_EE");
  TH1D* ZmmMass_DA_EB	 = (TH1D*) gROOT->FindObject("ZmmMass_DA_EB");
  TH1D* ZeeMass_DA	 = (TH1D*) gROOT->FindObject("ZeeMass_DA");
  TH1D* ZeeMass_DA_BB	 = (TH1D*) gROOT->FindObject("ZeeMass_DA_BB");
  TH1D* ZeeMass_DA_EE	 = (TH1D*) gROOT->FindObject("ZeeMass_DA_EE");
  TH1D* ZeeMass_DA_EB	 = (TH1D*) gROOT->FindObject("ZeeMass_DA_EB");
  TH1D* ZmmMass_CorMC	 = (TH1D*) gROOT->FindObject("ZmmMass_CorMC");
  TH1D* ZmmMass_CorMC_BB = (TH1D*) gROOT->FindObject("ZmmMass_CorMC_BB");
  TH1D* ZmmMass_CorMC_EE = (TH1D*) gROOT->FindObject("ZmmMass_CorMC_EE");
  TH1D* ZmmMass_CorMC_EB = (TH1D*) gROOT->FindObject("ZmmMass_CorMC_EB");
  TH1D* ZeeMass_CorMC	 = (TH1D*) gROOT->FindObject("ZeeMass_CorMC");
  TH1D* ZeeMass_CorMC_BB = (TH1D*) gROOT->FindObject("ZeeMass_CorMC_BB");
  TH1D* ZeeMass_CorMC_EE = (TH1D*) gROOT->FindObject("ZeeMass_CorMC_EE");
  TH1D* ZeeMass_CorMC_EB = (TH1D*) gROOT->FindObject("ZeeMass_CorMC_EB");
  ZmmMass_MC      ->SetDirectory(0);
  ZmmMass_MC_BB   ->SetDirectory(0);
  ZmmMass_MC_EE   ->SetDirectory(0);
  ZmmMass_MC_EB   ->SetDirectory(0);
  ZeeMass_MC      ->SetDirectory(0);
  ZeeMass_MC_BB   ->SetDirectory(0);
  ZeeMass_MC_EE   ->SetDirectory(0);
  ZeeMass_MC_EB   ->SetDirectory(0);
  ZmmMass_DA      ->SetDirectory(0);
  ZmmMass_DA_BB   ->SetDirectory(0);
  ZmmMass_DA_EE   ->SetDirectory(0);
  ZmmMass_DA_EB   ->SetDirectory(0);
  ZeeMass_DA      ->SetDirectory(0);
  ZeeMass_DA_BB   ->SetDirectory(0);
  ZeeMass_DA_EE   ->SetDirectory(0);
  ZeeMass_DA_EB   ->SetDirectory(0);
  ZmmMass_CorMC   ->SetDirectory(0);
  ZmmMass_CorMC_BB->SetDirectory(0);
  ZmmMass_CorMC_EE->SetDirectory(0);
  ZmmMass_CorMC_EB->SetDirectory(0);
  ZeeMass_CorMC   ->SetDirectory(0);
  ZeeMass_CorMC_BB->SetDirectory(0);
  ZeeMass_CorMC_EE->SetDirectory(0);
  ZeeMass_CorMC_EB->SetDirectory(0);
  ZmmMass_CorMC   ->Scale(1.10);
  ZmmMass_CorMC_BB->Scale(1.09);
  ZmmMass_CorMC_EE->Scale(1.05);
  ZmmMass_CorMC_EB->Scale(1.15);
  TCanvas *cv = new TCanvas("cv", "cv", 1000, 1000);
  cv->Divide(4,2);
  cv->cd(1);
  TLegend *legend1 = new TLegend(0.3,0.8,0.9,0.9);
  legend1->SetFillStyle(0);
  legend1->SetFillColor(kWhite);
  legend1->SetBorderSize(0);
  legend1->SetTextSize(0.04);
  legend1->SetTextFont(132);
  legend1->SetLineWidth(1);
  legend1->AddEntry(ZmmMass_DA   , "Data #mu#mu", "L");
  legend1->AddEntry(ZmmMass_MC   , "MC uncorrected", "L");
  legend1->AddEntry(ZmmMass_CorMC, "MC corrected", "L");
  ZmmMass_MC->SetMaximum(ZmmMass_MC->GetMaximum() * 1.2);
  ZmmMass_MC->SetLineColor(kRed);
  ZmmMass_MC->SetLineWidth(2);
  ZmmMass_MC->Draw("hist");
  ZmmMass_DA->SetLineColor(kBlue);
  ZmmMass_DA->SetLineWidth(2);
  ZmmMass_DA->Draw("e,same");
  ZmmMass_CorMC->SetLineColor(kBlack);
  ZmmMass_CorMC->SetLineWidth(2);
  ZmmMass_CorMC->Draw("same,hist");
  legend1->Draw();
  cv->cd(2);
  TLegend *legend2 = new TLegend(0.3,0.8,0.9,0.9);
  legend2->SetFillStyle(0);
  legend2->SetFillColor(kWhite);
  legend2->SetBorderSize(0);
  legend2->SetTextSize(0.04);
  legend2->SetTextFont(132);
  legend2->SetLineWidth(1);
  legend2->AddEntry(ZmmMass_DA_BB   , "Data #mu#mu barrel-barrel", "L");
  legend2->AddEntry(ZmmMass_MC_BB   , "MC uncorrected", "L");
  legend2->AddEntry(ZmmMass_CorMC_BB, "MC corrected", "L");
  ZmmMass_MC_BB->SetMaximum(ZmmMass_MC_BB->GetMaximum() * 1.2);
  ZmmMass_MC_BB->SetLineColor(kRed);
  ZmmMass_MC_BB->SetLineWidth(2);
  ZmmMass_MC_BB->Draw("hist");
  ZmmMass_DA_BB->SetLineColor(kBlue);
  ZmmMass_DA_BB->SetLineWidth(2);
  ZmmMass_DA_BB->Draw("e,same");
  ZmmMass_CorMC_BB->SetLineColor(kBlack);
  ZmmMass_CorMC_BB->SetLineWidth(2);
  ZmmMass_CorMC_BB->Draw("same,hist");
  legend2->Draw();
  cv->cd(3);
  TLegend *legend3 = new TLegend(0.3,0.8,0.9,0.9);
  legend3->SetFillStyle(0);
  legend3->SetFillColor(kWhite);
  legend3->SetBorderSize(0);
  legend3->SetTextSize(0.04);
  legend3->SetTextFont(132);
  legend3->SetLineWidth(1);
  legend3->AddEntry(ZmmMass_DA_EB   , "Data #mu#mu barrel-endcap", "L");
  legend3->AddEntry(ZmmMass_MC_EB   , "MC uncorrected", "L");
  legend3->AddEntry(ZmmMass_CorMC_EB, "MC corrected", "L");
  ZmmMass_MC_EB->SetMaximum(ZmmMass_MC_EB->GetMaximum() * 1.2);
  ZmmMass_MC_EB->SetLineColor(kRed);
  ZmmMass_MC_EB->SetLineWidth(2);
  ZmmMass_MC_EB->Draw("hist");
  ZmmMass_DA_EB->SetLineColor(kBlue);
  ZmmMass_DA_EB->SetLineWidth(2);
  ZmmMass_DA_EB->Draw("e,same");
  ZmmMass_CorMC_EB->SetLineColor(kBlack);
  ZmmMass_CorMC_EB->SetLineWidth(2);
  ZmmMass_CorMC_EB->Draw("same,hist");
  legend3->Draw();
  cv->cd(4);
  TLegend *legend4 = new TLegend(0.3,0.8,0.9,0.9);
  legend4->SetFillStyle(0);
  legend4->SetFillColor(kWhite);
  legend4->SetBorderSize(0);
  legend4->SetTextSize(0.04);
  legend4->SetTextFont(132);
  legend4->SetLineWidth(1);
  legend4->AddEntry(ZmmMass_DA_EE   , "Data #mu#mu endcap-endcap", "L");
  legend4->AddEntry(ZmmMass_MC_EE   , "MC uncorrected", "L");
  legend4->AddEntry(ZmmMass_CorMC_EE, "MC corrected", "L");
  ZmmMass_MC_EE->SetMaximum(ZmmMass_MC_EE->GetMaximum() * 1.2);
  ZmmMass_MC_EE->SetLineColor(kRed);
  ZmmMass_MC_EE->SetLineWidth(2);
  ZmmMass_MC_EE->Draw("hist");
  ZmmMass_DA_EE->SetLineColor(kBlue);
  ZmmMass_DA_EE->SetLineWidth(2);
  ZmmMass_DA_EE->Draw("e,same");
  ZmmMass_CorMC_EE->SetLineColor(kBlack);
  ZmmMass_CorMC_EE->SetLineWidth(2);
  ZmmMass_CorMC_EE->Draw("same,hist");
  legend4->Draw();
  cv->cd(5);
  TLegend *legend5 = new TLegend(0.3,0.8,0.9,0.9);
  legend5->SetFillStyle(0);
  legend5->SetFillColor(kWhite);
  legend5->SetBorderSize(0);
  legend5->SetTextSize(0.04);
  legend5->SetTextFont(132);
  legend5->SetLineWidth(1);
  legend5->AddEntry(ZeeMass_DA   , "Data ee", "L");
  legend5->AddEntry(ZeeMass_MC   , "MC uncorrected", "L");
  legend5->AddEntry(ZeeMass_CorMC, "MC corrected", "L");
  ZeeMass_MC->SetMaximum(ZeeMass_MC->GetMaximum() * 1.2);
  ZeeMass_MC->SetLineColor(kRed);
  ZeeMass_MC->SetLineWidth(2);
  ZeeMass_MC->Draw("hist");
  ZeeMass_DA->SetLineColor(kBlue);
  ZeeMass_DA->SetLineWidth(2);
  ZeeMass_DA->Draw("e,same");
  ZeeMass_CorMC->SetLineColor(kBlack);
  ZeeMass_CorMC->SetLineWidth(2);
  ZeeMass_CorMC->Draw("same,hist");
  legend5->Draw();
  cv->cd(6);
  TLegend *legend6 = new TLegend(0.3,0.8,0.9,0.9);
  legend6->SetFillStyle(0);
  legend6->SetFillColor(kWhite);
  legend6->SetBorderSize(0);
  legend6->SetTextSize(0.04);
  legend6->SetTextFont(132);
  legend6->SetLineWidth(1);
  legend6->AddEntry(ZeeMass_DA_BB   , "Data ee barrel-barrel", "L");
  legend6->AddEntry(ZeeMass_MC_BB   , "MC uncorrected", "L");
  legend6->AddEntry(ZeeMass_CorMC_BB, "MC corrected", "L");
  ZeeMass_MC_BB->SetMaximum(ZeeMass_MC_BB->GetMaximum() * 1.2);
  ZeeMass_MC_BB->SetLineColor(kRed);
  ZeeMass_MC_BB->SetLineWidth(2);
  ZeeMass_MC_BB->Draw("hist");
  ZeeMass_DA_BB->SetLineColor(kBlue);
  ZeeMass_DA_BB->SetLineWidth(2);
  ZeeMass_DA_BB->Draw("e,same");
  ZeeMass_CorMC_BB->SetLineColor(kBlack);
  ZeeMass_CorMC_BB->SetLineWidth(2);
  ZeeMass_CorMC_BB->Draw("same,hist");
  legend6->Draw();
  cv->cd(7);
  TLegend *legend7 = new TLegend(0.3,0.8,0.9,0.9);
  legend7->SetFillStyle(0);
  legend7->SetFillColor(kWhite);
  legend7->SetBorderSize(0);
  legend7->SetTextSize(0.04);
  legend7->SetTextFont(132);
  legend7->SetLineWidth(1);
  legend7->AddEntry(ZeeMass_DA_EB   , "Data ee barrel-endcap", "L");
  legend7->AddEntry(ZeeMass_MC_EB   , "MC uncorrected", "L");
  legend7->AddEntry(ZeeMass_CorMC_EB, "MC corrected", "L");
  ZeeMass_MC_EB->SetMaximum(ZeeMass_MC_EB->GetMaximum() * 1.2);
  ZeeMass_MC_EB->SetLineColor(kRed);
  ZeeMass_MC_EB->SetLineWidth(2);
  ZeeMass_MC_EB->Draw("hist");
  ZeeMass_DA_EB->SetLineColor(kBlue);
  ZeeMass_DA_EB->SetLineWidth(2);
  ZeeMass_DA_EB->Draw("e,same");
  ZeeMass_CorMC_EB->SetLineColor(kBlack);
  ZeeMass_CorMC_EB->SetLineWidth(2);
  ZeeMass_CorMC_EB->Draw("same,hist");
  legend7->Draw();
  cv->cd(8);
  TLegend *legend8 = new TLegend(0.3,0.8,0.9,0.9);
  legend8->SetFillStyle(0);
  legend8->SetFillColor(kWhite);
  legend8->SetBorderSize(0);
  legend8->SetTextSize(0.04);
  legend8->SetTextFont(132);
  legend8->SetLineWidth(1);
  legend8->AddEntry(ZeeMass_DA_EE   , "Data ee endcap-endcap", "L");
  legend8->AddEntry(ZeeMass_MC_EE   , "MC uncorrected", "L");
  legend8->AddEntry(ZeeMass_CorMC_EE, "MC corrected", "L");
  ZeeMass_MC_EE->SetMaximum(ZeeMass_MC_EE->GetMaximum() * 1.2);
  ZeeMass_MC_EE->SetLineColor(kRed);
  ZeeMass_MC_EE->SetLineWidth(2);
  ZeeMass_MC_EE->Draw("hist");
  ZeeMass_DA_EE->SetLineColor(kBlue);
  ZeeMass_DA_EE->SetLineWidth(2);
  ZeeMass_DA_EE->Draw("e,same");
  ZeeMass_CorMC_EE->SetLineColor(kBlack);
  ZeeMass_CorMC_EE->SetLineWidth(2);
  ZeeMass_CorMC_EE->Draw("same,hist");
  legend8->Draw();
  cv->SaveAs("test_zll.pdf");
}
