#include "TROOT.h"
#include "TFile.h"
#include "TLegend.h"
#include "TCanvas.h"
#include "TRandom.h"
#include "TH1D.h"
#include "TStyle.h"
#include <iostream>

void test_ZllNormalization(Int_t theReBin = 4){
  gROOT->SetStyle("Plain");
  gStyle->SetOptStat(0);
  TFile *_file0 = TFile::Open("zyield.root");
  _file0->cd(); 
  TH1D* ZmmMass_MC	 = (TH1D*) gROOT->FindObject("ZmmMass_MC");
  TH1D* ZmmMass_MC_BB	 = (TH1D*) gROOT->FindObject("ZmmMass_MC_BB");
  TH1D* ZmmMass_MC_EE	 = (TH1D*) gROOT->FindObject("ZmmMass_MC_EE");
  TH1D* ZmmMass_MC_EB	 = (TH1D*) gROOT->FindObject("ZmmMass_MC_EB");
  TH1D* ZeeMass_MC	 = (TH1D*) gROOT->FindObject("ZeeMass_MC");
  TH1D* ZeeMass_MC_BB	 = (TH1D*) gROOT->FindObject("ZeeMass_MC_BB");
  TH1D* ZeeMass_MC_EE	 = (TH1D*) gROOT->FindObject("ZeeMass_MC_EE");
  TH1D* ZeeMass_MC_EB	 = (TH1D*) gROOT->FindObject("ZeeMass_MC_EB");
  TH1D* ZmmMass_DA	 = (TH1D*) gROOT->FindObject("ZmmMass_DA");
  TH1D* ZmmMass_DA_BB	 = (TH1D*) gROOT->FindObject("ZmmMass_DA_BB");
  TH1D* ZmmMass_DA_EE	 = (TH1D*) gROOT->FindObject("ZmmMass_DA_EE");
  TH1D* ZmmMass_DA_EB	 = (TH1D*) gROOT->FindObject("ZmmMass_DA_EB");
  TH1D* ZeeMass_DA	 = (TH1D*) gROOT->FindObject("ZeeMass_DA");
  TH1D* ZeeMass_DA_BB	 = (TH1D*) gROOT->FindObject("ZeeMass_DA_BB");
  TH1D* ZeeMass_DA_EE	 = (TH1D*) gROOT->FindObject("ZeeMass_DA_EE");
  TH1D* ZeeMass_DA_EB	 = (TH1D*) gROOT->FindObject("ZeeMass_DA_EB");
  TH1D* ZmmMass_CorMC	 = (TH1D*) gROOT->FindObject("ZmmMass_CorMC");
  TH1D* ZmmMass_CorMC_BB = (TH1D*) gROOT->FindObject("ZmmMass_CorMC_BB");
  TH1D* ZmmMass_CorMC_EE = (TH1D*) gROOT->FindObject("ZmmMass_CorMC_EE");
  TH1D* ZmmMass_CorMC_EB = (TH1D*) gROOT->FindObject("ZmmMass_CorMC_EB");
  TH1D* ZeeMass_CorMC	 = (TH1D*) gROOT->FindObject("ZeeMass_CorMC");
  TH1D* ZeeMass_CorMC_BB = (TH1D*) gROOT->FindObject("ZeeMass_CorMC_BB");
  TH1D* ZeeMass_CorMC_EE = (TH1D*) gROOT->FindObject("ZeeMass_CorMC_EE");
  TH1D* ZeeMass_CorMC_EB = (TH1D*) gROOT->FindObject("ZeeMass_CorMC_EB");
  ZmmMass_MC      ->SetDirectory(0);
  ZmmMass_MC_BB   ->SetDirectory(0);
  ZmmMass_MC_EE   ->SetDirectory(0);
  ZmmMass_MC_EB   ->SetDirectory(0);
  ZeeMass_MC      ->SetDirectory(0);
  ZeeMass_MC_BB   ->SetDirectory(0);
  ZeeMass_MC_EE   ->SetDirectory(0);
  ZeeMass_MC_EB   ->SetDirectory(0);
  ZmmMass_DA      ->SetDirectory(0);
  ZmmMass_DA_BB   ->SetDirectory(0);
  ZmmMass_DA_EE   ->SetDirectory(0);
  ZmmMass_DA_EB   ->SetDirectory(0);
  ZeeMass_DA      ->SetDirectory(0);
  ZeeMass_DA_BB   ->SetDirectory(0);
  ZeeMass_DA_EE   ->SetDirectory(0);
  ZeeMass_DA_EB   ->SetDirectory(0);
  ZmmMass_CorMC   ->SetDirectory(0);
  ZmmMass_CorMC_BB->SetDirectory(0);
  ZmmMass_CorMC_EE->SetDirectory(0);
  ZmmMass_CorMC_EB->SetDirectory(0);
  ZeeMass_CorMC   ->SetDirectory(0);
  ZeeMass_CorMC_BB->SetDirectory(0);
  ZeeMass_CorMC_EE->SetDirectory(0);
  ZeeMass_CorMC_EB->SetDirectory(0);
  ZmmMass_MC      ->Rebin(theReBin);
  ZmmMass_MC_BB   ->Rebin(theReBin);
  ZmmMass_MC_EE   ->Rebin(theReBin);
  ZmmMass_MC_EB   ->Rebin(theReBin);
  ZeeMass_MC      ->Rebin(theReBin);
  ZeeMass_MC_BB   ->Rebin(theReBin);
  ZeeMass_MC_EE   ->Rebin(theReBin);
  ZeeMass_MC_EB   ->Rebin(theReBin);
  ZmmMass_DA      ->Rebin(theReBin);
  ZmmMass_DA_BB   ->Rebin(theReBin);
  ZmmMass_DA_EE   ->Rebin(theReBin);
  ZmmMass_DA_EB   ->Rebin(theReBin);
  ZeeMass_DA      ->Rebin(theReBin);
  ZeeMass_DA_BB   ->Rebin(theReBin);
  ZeeMass_DA_EE   ->Rebin(theReBin);
  ZeeMass_DA_EB   ->Rebin(theReBin);
  ZmmMass_CorMC   ->Rebin(theReBin);
  ZmmMass_CorMC_BB->Rebin(theReBin);
  ZmmMass_CorMC_EE->Rebin(theReBin);
  ZmmMass_CorMC_EB->Rebin(theReBin);
  ZeeMass_CorMC   ->Rebin(theReBin);
  ZeeMass_CorMC_BB->Rebin(theReBin);
  ZeeMass_CorMC_EE->Rebin(theReBin);
  ZeeMass_CorMC_EB->Rebin(theReBin);
       
  ZmmMass_CorMC   ->Scale(ZmmMass_DA   ->GetSumOfWeights()/ZmmMass_CorMC   ->GetSumOfWeights());
  ZmmMass_CorMC_BB->Scale(ZmmMass_DA_BB->GetSumOfWeights()/ZmmMass_CorMC_BB->GetSumOfWeights());
  ZmmMass_CorMC_EB->Scale(ZmmMass_DA_EB->GetSumOfWeights()/ZmmMass_CorMC_EB->GetSumOfWeights());
  ZmmMass_CorMC_EE->Scale(ZmmMass_DA_EE->GetSumOfWeights()/ZmmMass_CorMC_EE->GetSumOfWeights());
  ZmmMass_MC   ->Scale(ZmmMass_DA   ->GetSumOfWeights()   /ZmmMass_MC   ->GetSumOfWeights());
  ZmmMass_MC_BB->Scale(ZmmMass_DA_BB->GetSumOfWeights()   /ZmmMass_MC_BB->GetSumOfWeights());
  ZmmMass_MC_EB->Scale(ZmmMass_DA_EB->GetSumOfWeights()   /ZmmMass_MC_EB->GetSumOfWeights());
  ZmmMass_MC_EE->Scale(ZmmMass_DA_EE->GetSumOfWeights()   /ZmmMass_MC_EE->GetSumOfWeights());
  ZeeMass_CorMC   ->Scale(ZeeMass_DA   ->GetSumOfWeights()/ZeeMass_CorMC   ->GetSumOfWeights());
  ZeeMass_CorMC_BB->Scale(ZeeMass_DA_BB->GetSumOfWeights()/ZeeMass_CorMC_BB->GetSumOfWeights());
  ZeeMass_CorMC_EB->Scale(ZeeMass_DA_EB->GetSumOfWeights()/ZeeMass_CorMC_EB->GetSumOfWeights());
  ZeeMass_CorMC_EE->Scale(ZeeMass_DA_EE->GetSumOfWeights()/ZeeMass_CorMC_EE->GetSumOfWeights());
  ZeeMass_MC   ->Scale(ZeeMass_DA   ->GetSumOfWeights()   /ZeeMass_MC   ->GetSumOfWeights());
  ZeeMass_MC_BB->Scale(ZeeMass_DA_BB->GetSumOfWeights()   /ZeeMass_MC_BB->GetSumOfWeights());
  ZeeMass_MC_EB->Scale(ZeeMass_DA_EB->GetSumOfWeights()   /ZeeMass_MC_EB->GetSumOfWeights());
  ZeeMass_MC_EE->Scale(ZeeMass_DA_EE->GetSumOfWeights()   /ZeeMass_MC_EE->GetSumOfWeights());
  TCanvas *cv = new TCanvas("cv", "cv", 1000, 1000);
  cv->Divide(4,2);
  cv->cd(1);
  TLegend *legend1 = new TLegend(0.3,0.8,0.9,0.9);
  legend1->SetFillStyle(0);
  legend1->SetFillColor(kWhite);
  legend1->SetBorderSize(0);
  legend1->SetTextSize(0.04);
  legend1->SetTextFont(132);
  legend1->SetLineWidth(1);
  legend1->AddEntry(ZmmMass_DA   , "Data #mu#mu", "L");
  legend1->AddEntry(ZmmMass_MC   , "MC uncorrected", "L");
  legend1->AddEntry(ZmmMass_CorMC, "MC corrected", "L");
  ZmmMass_MC->SetMaximum(ZmmMass_MC->GetMaximum() * 1.2);
  ZmmMass_MC->SetLineColor(kRed);
  ZmmMass_MC->SetLineWidth(2);
  ZmmMass_MC->Draw("hist");
  ZmmMass_DA->SetLineColor(kBlue);
  ZmmMass_DA->SetLineWidth(2);
  ZmmMass_DA->Draw("e,same");
  ZmmMass_CorMC->SetLineColor(kBlack);
  ZmmMass_CorMC->SetLineWidth(2);
  ZmmMass_CorMC->Draw("same,hist");
  legend1->Draw();
  cv->cd(2);
  TLegend *legend2 = new TLegend(0.3,0.8,0.9,0.9);
  legend2->SetFillStyle(0);
  legend2->SetFillColor(kWhite);
  legend2->SetBorderSize(0);
  legend2->SetTextSize(0.04);
  legend2->SetTextFont(132);
  legend2->SetLineWidth(1);
  legend2->AddEntry(ZmmMass_DA_BB   , "Data #mu#mu barrel-barrel", "L");
  legend2->AddEntry(ZmmMass_MC_BB   , "MC uncorrected", "L");
  legend2->AddEntry(ZmmMass_CorMC_BB, "MC corrected", "L");
  ZmmMass_MC_BB->SetMaximum(ZmmMass_MC_BB->GetMaximum() * 1.2);
  ZmmMass_MC_BB->SetLineColor(kRed);
  ZmmMass_MC_BB->SetLineWidth(2);
  ZmmMass_MC_BB->Draw("hist");
  ZmmMass_DA_BB->SetLineColor(kBlue);
  ZmmMass_DA_BB->SetLineWidth(2);
  ZmmMass_DA_BB->Draw("e,same");
  ZmmMass_CorMC_BB->SetLineColor(kBlack);
  ZmmMass_CorMC_BB->SetLineWidth(2);
  ZmmMass_CorMC_BB->Draw("same,hist");
  legend2->Draw();
  cv->cd(3);
  TLegend *legend3 = new TLegend(0.3,0.8,0.9,0.9);
  legend3->SetFillStyle(0);
  legend3->SetFillColor(kWhite);
  legend3->SetBorderSize(0);
  legend3->SetTextSize(0.04);
  legend3->SetTextFont(132);
  legend3->SetLineWidth(1);
  legend3->AddEntry(ZmmMass_DA_EB   , "Data #mu#mu barrel-endcap", "L");
  legend3->AddEntry(ZmmMass_MC_EB   , "MC uncorrected", "L");
  legend3->AddEntry(ZmmMass_CorMC_EB, "MC corrected", "L");
  ZmmMass_MC_EB->SetMaximum(ZmmMass_MC_EB->GetMaximum() * 1.2);
  ZmmMass_MC_EB->SetLineColor(kRed);
  ZmmMass_MC_EB->SetLineWidth(2);
  ZmmMass_MC_EB->Draw("hist");
  ZmmMass_DA_EB->SetLineColor(kBlue);
  ZmmMass_DA_EB->SetLineWidth(2);
  ZmmMass_DA_EB->Draw("e,same");
  ZmmMass_CorMC_EB->SetLineColor(kBlack);
  ZmmMass_CorMC_EB->SetLineWidth(2);
  ZmmMass_CorMC_EB->Draw("same,hist");
  legend3->Draw();
  cv->cd(4);
  TLegend *legend4 = new TLegend(0.3,0.8,0.9,0.9);
  legend4->SetFillStyle(0);
  legend4->SetFillColor(kWhite);
  legend4->SetBorderSize(0);
  legend4->SetTextSize(0.04);
  legend4->SetTextFont(132);
  legend4->SetLineWidth(1);
  legend4->AddEntry(ZmmMass_DA_EE   , "Data #mu#mu endcap-endcap", "L");
  legend4->AddEntry(ZmmMass_MC_EE   , "MC uncorrected", "L");
  legend4->AddEntry(ZmmMass_CorMC_EE, "MC corrected", "L");
  ZmmMass_MC_EE->SetMaximum(ZmmMass_MC_EE->GetMaximum() * 1.2);
  ZmmMass_MC_EE->SetLineColor(kRed);
  ZmmMass_MC_EE->SetLineWidth(2);
  ZmmMass_MC_EE->Draw("hist");
  ZmmMass_DA_EE->SetLineColor(kBlue);
  ZmmMass_DA_EE->SetLineWidth(2);
  ZmmMass_DA_EE->Draw("e,same");
  ZmmMass_CorMC_EE->SetLineColor(kBlack);
  ZmmMass_CorMC_EE->SetLineWidth(2);
  ZmmMass_CorMC_EE->Draw("same,hist");
  legend4->Draw();
  cv->cd(5);
  TLegend *legend5 = new TLegend(0.3,0.8,0.9,0.9);
  legend5->SetFillStyle(0);
  legend5->SetFillColor(kWhite);
  legend5->SetBorderSize(0);
  legend5->SetTextSize(0.04);
  legend5->SetTextFont(132);
  legend5->SetLineWidth(1);
  legend5->AddEntry(ZeeMass_DA   , "Data ee", "L");
  legend5->AddEntry(ZeeMass_MC   , "MC uncorrected", "L");
  legend5->AddEntry(ZeeMass_CorMC, "MC corrected", "L");
  ZeeMass_MC->SetMaximum(ZeeMass_MC->GetMaximum() * 1.2);
  ZeeMass_MC->SetLineColor(kRed);
  ZeeMass_MC->SetLineWidth(2);
  ZeeMass_MC->Draw("hist");
  ZeeMass_DA->SetLineColor(kBlue);
  ZeeMass_DA->SetLineWidth(2);
  ZeeMass_DA->Draw("e,same");
  ZeeMass_CorMC->SetLineColor(kBlack);
  ZeeMass_CorMC->SetLineWidth(2);
  ZeeMass_CorMC->Draw("same,hist");
  legend5->Draw();
  cv->cd(6);
  TLegend *legend6 = new TLegend(0.3,0.8,0.9,0.9);
  legend6->SetFillStyle(0);
  legend6->SetFillColor(kWhite);
  legend6->SetBorderSize(0);
  legend6->SetTextSize(0.04);
  legend6->SetTextFont(132);
  legend6->SetLineWidth(1);
  legend6->AddEntry(ZeeMass_DA_BB   , "Data ee barrel-barrel", "L");
  legend6->AddEntry(ZeeMass_MC_BB   , "MC uncorrected", "L");
  legend6->AddEntry(ZeeMass_CorMC_BB, "MC corrected", "L");
  ZeeMass_MC_BB->SetMaximum(ZeeMass_MC_BB->GetMaximum() * 1.2);
  ZeeMass_MC_BB->SetLineColor(kRed);
  ZeeMass_MC_BB->SetLineWidth(2);
  ZeeMass_MC_BB->Draw("hist");
  ZeeMass_DA_BB->SetLineColor(kBlue);
  ZeeMass_DA_BB->SetLineWidth(2);
  ZeeMass_DA_BB->Draw("e,same");
  ZeeMass_CorMC_BB->SetLineColor(kBlack);
  ZeeMass_CorMC_BB->SetLineWidth(2);
  ZeeMass_CorMC_BB->Draw("same,hist");
  legend6->Draw();
  cv->cd(7);
  TLegend *legend7 = new TLegend(0.3,0.8,0.9,0.9);
  legend7->SetFillStyle(0);
  legend7->SetFillColor(kWhite);
  legend7->SetBorderSize(0);
  legend7->SetTextSize(0.04);
  legend7->SetTextFont(132);
  legend7->SetLineWidth(1);
  legend7->AddEntry(ZeeMass_DA_EB   , "Data ee barrel-endcap", "L");
  legend7->AddEntry(ZeeMass_MC_EB   , "MC uncorrected", "L");
  legend7->AddEntry(ZeeMass_CorMC_EB, "MC corrected", "L");
  ZeeMass_MC_EB->SetMaximum(ZeeMass_MC_EB->GetMaximum() * 1.2);
  ZeeMass_MC_EB->SetLineColor(kRed);
  ZeeMass_MC_EB->SetLineWidth(2);
  ZeeMass_MC_EB->Draw("hist");
  ZeeMass_DA_EB->SetLineColor(kBlue);
  ZeeMass_DA_EB->SetLineWidth(2);
  ZeeMass_DA_EB->Draw("e,same");
  ZeeMass_CorMC_EB->SetLineColor(kBlack);
  ZeeMass_CorMC_EB->SetLineWidth(2);
  ZeeMass_CorMC_EB->Draw("same,hist");
  legend7->Draw();
  cv->cd(8);
  TLegend *legend8 = new TLegend(0.3,0.8,0.9,0.9);
  legend8->SetFillStyle(0);
  legend8->SetFillColor(kWhite);
  legend8->SetBorderSize(0);
  legend8->SetTextSize(0.04);
  legend8->SetTextFont(132);
  legend8->SetLineWidth(1);
  legend8->AddEntry(ZeeMass_DA_EE   , "Data ee endcap-endcap", "L");
  legend8->AddEntry(ZeeMass_MC_EE   , "MC uncorrected", "L");
  legend8->AddEntry(ZeeMass_CorMC_EE, "MC corrected", "L");
  ZeeMass_MC_EE->SetMaximum(ZeeMass_MC_EE->GetMaximum() * 1.2);
  ZeeMass_MC_EE->SetLineColor(kRed);
  ZeeMass_MC_EE->SetLineWidth(2);
  ZeeMass_MC_EE->Draw("hist");
  ZeeMass_DA_EE->SetLineColor(kBlue);
  ZeeMass_DA_EE->SetLineWidth(2);
  ZeeMass_DA_EE->Draw("e,same");
  ZeeMass_CorMC_EE->SetLineColor(kBlack);
  ZeeMass_CorMC_EE->SetLineWidth(2);
  ZeeMass_CorMC_EE->Draw("same,hist");
  legend8->Draw();
  cv->SaveAs("test_lep_zll.pdf");
  
  TH1D* Zll0Met_MC_X	    	   = (TH1D*) gROOT->FindObject("Zll0Met_MC_X");	    
  TH1D* Zll0Met_MC_Y	    	   = (TH1D*) gROOT->FindObject("Zll0Met_MC_Y");	    
  TH1D* Zll0TrackMet_MC_X   	   = (TH1D*) gROOT->FindObject("Zll0TrackMet_MC_X");   
  TH1D* Zll0TrackMet_MC_Y   	   = (TH1D*) gROOT->FindObject("Zll0TrackMet_MC_Y");   
  TH1D* Zll0Met_DA_X	    	   = (TH1D*) gROOT->FindObject("Zll0Met_DA_X");	    
  TH1D* Zll0Met_DA_Y	    	   = (TH1D*) gROOT->FindObject("Zll0Met_DA_Y");	    
  TH1D* Zll0TrackMet_DA_X   	   = (TH1D*) gROOT->FindObject("Zll0TrackMet_DA_X");   
  TH1D* Zll0TrackMet_DA_Y   	   = (TH1D*) gROOT->FindObject("Zll0TrackMet_DA_Y");   
  TH1D* Zll0Met_CorMC_X     	   = (TH1D*) gROOT->FindObject("Zll0Met_CorMC_X");     
  TH1D* Zll0Met_CorMC_Y     	   = (TH1D*) gROOT->FindObject("Zll0Met_CorMC_Y");     
  TH1D* Zll0TrackMet_CorMC_X	   = (TH1D*) gROOT->FindObject("Zll0TrackMet_CorMC_X");
  TH1D* Zll0TrackMet_CorMC_Y	   = (TH1D*) gROOT->FindObject("Zll0TrackMet_CorMC_Y");
  TH1D* Zll1Met_MC_X	    	   = (TH1D*) gROOT->FindObject("Zll1Met_MC_X");	    
  TH1D* Zll1Met_MC_Y	    	   = (TH1D*) gROOT->FindObject("Zll1Met_MC_Y");	    
  TH1D* Zll1TrackMet_MC_X   	   = (TH1D*) gROOT->FindObject("Zll1TrackMet_MC_X");  
  TH1D* Zll1TrackMet_MC_Y   	   = (TH1D*) gROOT->FindObject("Zll1TrackMet_MC_Y");   
  TH1D* Zll1Met_DA_X	    	   = (TH1D*) gROOT->FindObject("Zll1Met_DA_X");	    
  TH1D* Zll1Met_DA_Y	    	   = (TH1D*) gROOT->FindObject("Zll1Met_DA_Y");	    
  TH1D* Zll1TrackMet_DA_X   	   = (TH1D*) gROOT->FindObject("Zll1TrackMet_DA_X");   
  TH1D* Zll1TrackMet_DA_Y   	   = (TH1D*) gROOT->FindObject("Zll1TrackMet_DA_Y");   
  TH1D* Zll1Met_CorMC_X     	   = (TH1D*) gROOT->FindObject("Zll1Met_CorMC_X");     
  TH1D* Zll1Met_CorMC_Y     	   = (TH1D*) gROOT->FindObject("Zll1Met_CorMC_Y");     
  TH1D* Zll1TrackMet_CorMC_X	   = (TH1D*) gROOT->FindObject("Zll1TrackMet_CorMC_X");
  TH1D* Zll1TrackMet_CorMC_Y	   = (TH1D*) gROOT->FindObject("Zll1TrackMet_CorMC_Y");
  TH1D* Zll2Met_MC_X	    	   = (TH1D*) gROOT->FindObject("Zll2Met_MC_X");	    
  TH1D* Zll2Met_MC_Y	    	   = (TH1D*) gROOT->FindObject("Zll2Met_MC_Y");	    
  TH1D* Zll2TrackMet_MC_X   	   = (TH1D*) gROOT->FindObject("Zll2TrackMet_MC_X");   
  TH1D* Zll2TrackMet_MC_Y   	   = (TH1D*) gROOT->FindObject("Zll2TrackMet_MC_Y");   
  TH1D* Zll2Met_DA_X	    	   = (TH1D*) gROOT->FindObject("Zll2Met_DA_X");	    
  TH1D* Zll2Met_DA_Y	    	   = (TH1D*) gROOT->FindObject("Zll2Met_DA_Y");	    
  TH1D* Zll2TrackMet_DA_X   	   = (TH1D*) gROOT->FindObject("Zll2TrackMet_DA_X");   
  TH1D* Zll2TrackMet_DA_Y   	   = (TH1D*) gROOT->FindObject("Zll2TrackMet_DA_Y");   
  TH1D* Zll2Met_CorMC_X     	   = (TH1D*) gROOT->FindObject("Zll2Met_CorMC_X");     
  TH1D* Zll2Met_CorMC_Y     	   = (TH1D*) gROOT->FindObject("Zll2Met_CorMC_Y");     
  TH1D* Zll2TrackMet_CorMC_X	   = (TH1D*) gROOT->FindObject("Zll2TrackMet_CorMC_X");
  TH1D* Zll2TrackMet_CorMC_Y	   = (TH1D*) gROOT->FindObject("Zll2TrackMet_CorMC_Y");
  Zll0Met_MC_X        ->SetDirectory(0);
  Zll0Met_MC_Y        ->SetDirectory(0);
  Zll0TrackMet_MC_X   ->SetDirectory(0);
  Zll0TrackMet_MC_Y   ->SetDirectory(0);
  Zll0Met_DA_X        ->SetDirectory(0);
  Zll0Met_DA_Y        ->SetDirectory(0);
  Zll0TrackMet_DA_X   ->SetDirectory(0);
  Zll0TrackMet_DA_Y   ->SetDirectory(0);
  Zll0Met_CorMC_X     ->SetDirectory(0);
  Zll0Met_CorMC_Y     ->SetDirectory(0);
  Zll0TrackMet_CorMC_X->SetDirectory(0);
  Zll0TrackMet_CorMC_Y->SetDirectory(0);
  Zll1Met_MC_X        ->SetDirectory(0);
  Zll1Met_MC_Y        ->SetDirectory(0);
  Zll1TrackMet_MC_X   ->SetDirectory(0);
  Zll1TrackMet_MC_Y   ->SetDirectory(0);
  Zll1Met_DA_X        ->SetDirectory(0);
  Zll1Met_DA_Y        ->SetDirectory(0);
  Zll1TrackMet_DA_X   ->SetDirectory(0);
  Zll1TrackMet_DA_Y   ->SetDirectory(0);
  Zll1Met_CorMC_X     ->SetDirectory(0);
  Zll1Met_CorMC_Y     ->SetDirectory(0);
  Zll1TrackMet_CorMC_X->SetDirectory(0);
  Zll1TrackMet_CorMC_Y->SetDirectory(0);
  Zll2Met_MC_X        ->SetDirectory(0);
  Zll2Met_MC_Y        ->SetDirectory(0);
  Zll2TrackMet_MC_X   ->SetDirectory(0);
  Zll2TrackMet_MC_Y   ->SetDirectory(0);
  Zll2Met_DA_X        ->SetDirectory(0);
  Zll2Met_DA_Y        ->SetDirectory(0);
  Zll2TrackMet_DA_X   ->SetDirectory(0);
  Zll2TrackMet_DA_Y   ->SetDirectory(0);
  Zll2Met_CorMC_X     ->SetDirectory(0);
  Zll2Met_CorMC_Y     ->SetDirectory(0);
  Zll2TrackMet_CorMC_X->SetDirectory(0);
  Zll2TrackMet_CorMC_Y->SetDirectory(0);
  Zll0Met_MC_X        ->Rebin(theReBin);
  Zll0Met_MC_Y        ->Rebin(theReBin);
  Zll0TrackMet_MC_X   ->Rebin(theReBin);
  Zll0TrackMet_MC_Y   ->Rebin(theReBin);
  Zll0Met_DA_X        ->Rebin(theReBin);
  Zll0Met_DA_Y        ->Rebin(theReBin);
  Zll0TrackMet_DA_X   ->Rebin(theReBin);
  Zll0TrackMet_DA_Y   ->Rebin(theReBin);
  Zll0Met_CorMC_X     ->Rebin(theReBin);
  Zll0Met_CorMC_Y     ->Rebin(theReBin);
  Zll0TrackMet_CorMC_X->Rebin(theReBin);
  Zll0TrackMet_CorMC_Y->Rebin(theReBin);
  Zll1Met_MC_X        ->Rebin(theReBin);
  Zll1Met_MC_Y        ->Rebin(theReBin);
  Zll1TrackMet_MC_X   ->Rebin(theReBin);
  Zll1TrackMet_MC_Y   ->Rebin(theReBin);
  Zll1Met_DA_X        ->Rebin(theReBin);
  Zll1Met_DA_Y        ->Rebin(theReBin);
  Zll1TrackMet_DA_X   ->Rebin(theReBin);
  Zll1TrackMet_DA_Y   ->Rebin(theReBin);
  Zll1Met_CorMC_X     ->Rebin(theReBin);
  Zll1Met_CorMC_Y     ->Rebin(theReBin);
  Zll1TrackMet_CorMC_X->Rebin(theReBin);
  Zll1TrackMet_CorMC_Y->Rebin(theReBin);
  Zll2Met_MC_X        ->Rebin(theReBin);
  Zll2Met_MC_Y        ->Rebin(theReBin);
  Zll2TrackMet_MC_X   ->Rebin(theReBin);
  Zll2TrackMet_MC_Y   ->Rebin(theReBin);
  Zll2Met_DA_X        ->Rebin(theReBin);
  Zll2Met_DA_Y        ->Rebin(theReBin);
  Zll2TrackMet_DA_X   ->Rebin(theReBin);
  Zll2TrackMet_DA_Y   ->Rebin(theReBin);
  Zll2Met_CorMC_X     ->Rebin(theReBin);
  Zll2Met_CorMC_Y     ->Rebin(theReBin);
  Zll2TrackMet_CorMC_X->Rebin(theReBin);
  Zll2TrackMet_CorMC_Y->Rebin(theReBin);
  Zll0Met_MC_X     ->Scale(Zll0Met_DA_X     ->GetSumOfWeights()/Zll0Met_MC_X     ->GetSumOfWeights());
  Zll0Met_MC_Y     ->Scale(Zll0Met_DA_Y     ->GetSumOfWeights()/Zll0Met_MC_Y     ->GetSumOfWeights());
  Zll0TrackMet_MC_X->Scale(Zll0TrackMet_DA_X->GetSumOfWeights()/Zll0TrackMet_MC_X->GetSumOfWeights());
  Zll0TrackMet_MC_Y->Scale(Zll0TrackMet_DA_Y->GetSumOfWeights()/Zll0TrackMet_MC_Y->GetSumOfWeights());
  Zll0Met_CorMC_X     ->Scale(Zll0Met_DA_X     ->GetSumOfWeights()/Zll0Met_CorMC_X     ->GetSumOfWeights());
  Zll0Met_CorMC_Y     ->Scale(Zll0Met_DA_Y     ->GetSumOfWeights()/Zll0Met_CorMC_Y     ->GetSumOfWeights());
  Zll0TrackMet_CorMC_X->Scale(Zll0TrackMet_DA_X->GetSumOfWeights()/Zll0TrackMet_CorMC_X->GetSumOfWeights());
  Zll0TrackMet_CorMC_Y->Scale(Zll0TrackMet_DA_Y->GetSumOfWeights()/Zll0TrackMet_CorMC_Y->GetSumOfWeights());
  Zll1Met_MC_X     ->Scale(Zll1Met_DA_X     ->GetSumOfWeights()/Zll1Met_MC_X     ->GetSumOfWeights());
  Zll1Met_MC_Y     ->Scale(Zll1Met_DA_Y     ->GetSumOfWeights()/Zll1Met_MC_Y     ->GetSumOfWeights());
  Zll1TrackMet_MC_X->Scale(Zll1TrackMet_DA_X->GetSumOfWeights()/Zll1TrackMet_MC_X->GetSumOfWeights());
  Zll1TrackMet_MC_Y->Scale(Zll1TrackMet_DA_Y->GetSumOfWeights()/Zll1TrackMet_MC_Y->GetSumOfWeights());
  Zll1Met_CorMC_X     ->Scale(Zll1Met_DA_X     ->GetSumOfWeights()/Zll1Met_CorMC_X     ->GetSumOfWeights());
  Zll1Met_CorMC_Y     ->Scale(Zll1Met_DA_Y     ->GetSumOfWeights()/Zll1Met_CorMC_Y     ->GetSumOfWeights());
  Zll1TrackMet_CorMC_X->Scale(Zll1TrackMet_DA_X->GetSumOfWeights()/Zll1TrackMet_CorMC_X->GetSumOfWeights());
  Zll1TrackMet_CorMC_Y->Scale(Zll1TrackMet_DA_Y->GetSumOfWeights()/Zll1TrackMet_CorMC_Y->GetSumOfWeights());
  Zll2Met_MC_X     ->Scale(Zll2Met_DA_X     ->GetSumOfWeights()/Zll2Met_MC_X     ->GetSumOfWeights());
  Zll2Met_MC_Y     ->Scale(Zll2Met_DA_Y     ->GetSumOfWeights()/Zll2Met_MC_Y     ->GetSumOfWeights());
  Zll2TrackMet_MC_X->Scale(Zll2TrackMet_DA_X->GetSumOfWeights()/Zll2TrackMet_MC_X->GetSumOfWeights());
  Zll2TrackMet_MC_Y->Scale(Zll2TrackMet_DA_Y->GetSumOfWeights()/Zll2TrackMet_MC_Y->GetSumOfWeights());
  Zll2Met_CorMC_X     ->Scale(Zll2Met_DA_X     ->GetSumOfWeights()/Zll2Met_CorMC_X     ->GetSumOfWeights());
  Zll2Met_CorMC_Y     ->Scale(Zll2Met_DA_Y     ->GetSumOfWeights()/Zll2Met_CorMC_Y     ->GetSumOfWeights());
  Zll2TrackMet_CorMC_X->Scale(Zll2TrackMet_DA_X->GetSumOfWeights()/Zll2TrackMet_CorMC_X->GetSumOfWeights());
  Zll2TrackMet_CorMC_Y->Scale(Zll2TrackMet_DA_Y->GetSumOfWeights()/Zll2TrackMet_CorMC_Y->GetSumOfWeights());

  TCanvas *cv0 = new TCanvas("cv0", "cv0", 1000, 1000);
  cv0->Divide(2,2);
  cv0->cd(1);
  TLegend *legend01 = new TLegend(0.3,0.8,0.9,0.9);
  legend01->SetFillStyle(0);
  legend01->SetFillColor(kWhite);
  legend01->SetBorderSize(0);
  legend01->SetTextSize(0.04);
  legend01->SetTextFont(132);
  legend01->SetLineWidth(1);
  legend01->AddEntry(Zll0Met_DA_X   , "Data metX 0-jet", "L");
  legend01->AddEntry(Zll0Met_MC_X   , "MC uncorrected", "L");
  legend01->AddEntry(Zll0Met_CorMC_X, "MC corrected", "L");
  Zll0Met_MC_X->SetMaximum(Zll0Met_MC_X->GetMaximum() * 1.2);
  Zll0Met_MC_X->SetLineColor(kRed);
  Zll0Met_MC_X->SetLineWidth(2);
  Zll0Met_MC_X->Draw("hist");
  Zll0Met_DA_X->SetLineColor(kBlue);
  Zll0Met_DA_X->SetLineWidth(2);
  Zll0Met_DA_X->Draw("e,same");
  Zll0Met_CorMC_X->SetLineColor(kBlack);
  Zll0Met_CorMC_X->SetLineWidth(2);
  Zll0Met_CorMC_X->Draw("same,hist");
  legend01->Draw();
  cv0->cd(2);
  TLegend *legend02 = new TLegend(0.3,0.8,0.9,0.9);
  legend02->SetFillStyle(0);
  legend02->SetFillColor(kWhite);
  legend02->SetBorderSize(0);
  legend02->SetTextSize(0.04);
  legend02->SetTextFont(132);
  legend02->SetLineWidth(1);
  legend02->AddEntry(Zll0Met_DA_Y   , "Data metY 0-jet", "L");
  legend02->AddEntry(Zll0Met_MC_Y   , "MC uncorrected", "L");
  legend02->AddEntry(Zll0Met_CorMC_Y, "MC corrected", "L");
  Zll0Met_MC_Y->SetMaximum(Zll0Met_MC_Y->GetMaximum() * 1.2);
  Zll0Met_MC_Y->SetLineColor(kRed);
  Zll0Met_MC_Y->SetLineWidth(2);
  Zll0Met_MC_Y->Draw("hist");
  Zll0Met_DA_Y->SetLineColor(kBlue);
  Zll0Met_DA_Y->SetLineWidth(2);
  Zll0Met_DA_Y->Draw("e,same");
  Zll0Met_CorMC_Y->SetLineColor(kBlack);
  Zll0Met_CorMC_Y->SetLineWidth(2);
  Zll0Met_CorMC_Y->Draw("same,hist");
  legend02->Draw();
  cv0->cd(3);
  TLegend *legend03 = new TLegend(0.3,0.8,0.9,0.9);
  legend03->SetFillStyle(0);
  legend03->SetFillColor(kWhite);
  legend03->SetBorderSize(0);
  legend03->SetTextSize(0.04);
  legend03->SetTextFont(132);
  legend03->SetLineWidth(1);
  legend03->AddEntry(Zll0TrackMet_DA_X   , "Data TrackMetX 0-jet", "L");
  legend03->AddEntry(Zll0TrackMet_MC_X   , "MC uncorrected", "L");
  legend03->AddEntry(Zll0TrackMet_CorMC_X, "MC corrected", "L");
  Zll0TrackMet_MC_X->SetMaximum(Zll0TrackMet_MC_X->GetMaximum() * 1.2);
  Zll0TrackMet_MC_X->SetLineColor(kRed);
  Zll0TrackMet_MC_X->SetLineWidth(2);
  Zll0TrackMet_MC_X->Draw("hist");
  Zll0TrackMet_DA_X->SetLineColor(kBlue);
  Zll0TrackMet_DA_X->SetLineWidth(2);
  Zll0TrackMet_DA_X->Draw("e,same");
  Zll0TrackMet_CorMC_X->SetLineColor(kBlack);
  Zll0TrackMet_CorMC_X->SetLineWidth(2);
  Zll0TrackMet_CorMC_X->Draw("same,hist");
  legend03->Draw();
  cv0->cd(4);
  TLegend *legend04 = new TLegend(0.3,0.8,0.9,0.9);
  legend04->SetFillStyle(0);
  legend04->SetFillColor(kWhite);
  legend04->SetBorderSize(0);
  legend04->SetTextSize(0.04);
  legend04->SetTextFont(132);
  legend04->SetLineWidth(1);
  legend04->AddEntry(Zll0TrackMet_DA_Y   , "Data TrackMetY 0-jet", "L");
  legend04->AddEntry(Zll0TrackMet_MC_Y   , "MC uncorrected", "L");
  legend04->AddEntry(Zll0TrackMet_CorMC_Y, "MC corrected", "L");
  Zll0TrackMet_MC_Y->SetMaximum(Zll0TrackMet_MC_Y->GetMaximum() * 1.2);
  Zll0TrackMet_MC_Y->SetLineColor(kRed);
  Zll0TrackMet_MC_Y->SetLineWidth(2);
  Zll0TrackMet_MC_Y->Draw("hist");
  Zll0TrackMet_DA_Y->SetLineColor(kBlue);
  Zll0TrackMet_DA_Y->SetLineWidth(2);
  Zll0TrackMet_DA_Y->Draw("e,same");
  Zll0TrackMet_CorMC_Y->SetLineColor(kBlack);
  Zll0TrackMet_CorMC_Y->SetLineWidth(2);
  Zll0TrackMet_CorMC_Y->Draw("same,hist");
  legend04->Draw();
  cv0->SaveAs("test0_met_zll.pdf");
  
  TCanvas *cv1 = new TCanvas("cv1", "cv1", 1000, 1000);
  cv1->Divide(2,2);
  cv1->cd(1);
  TLegend *legend11 = new TLegend(0.3,0.8,0.9,0.9);
  legend11->SetFillStyle(0);
  legend11->SetFillColor(kWhite);
  legend11->SetBorderSize(0);
  legend11->SetTextSize(0.04);
  legend11->SetTextFont(132);
  legend11->SetLineWidth(1);
  legend11->AddEntry(Zll1Met_DA_X   , "Data metX 1-jet", "L");
  legend11->AddEntry(Zll1Met_MC_X   , "MC uncorrected", "L");
  legend11->AddEntry(Zll1Met_CorMC_X, "MC corrected", "L");
  Zll1Met_MC_X->SetMaximum(Zll1Met_MC_X->GetMaximum() * 1.2);
  Zll1Met_MC_X->SetLineColor(kRed);
  Zll1Met_MC_X->SetLineWidth(2);
  Zll1Met_MC_X->Draw("hist");
  Zll1Met_DA_X->SetLineColor(kBlue);
  Zll1Met_DA_X->SetLineWidth(2);
  Zll1Met_DA_X->Draw("e,same");
  Zll1Met_CorMC_X->SetLineColor(kBlack);
  Zll1Met_CorMC_X->SetLineWidth(2);
  Zll1Met_CorMC_X->Draw("same,hist");
  legend11->Draw();
  cv1->cd(2);
  TLegend *legend12 = new TLegend(0.3,0.8,0.9,0.9);
  legend12->SetFillStyle(0);
  legend12->SetFillColor(kWhite);
  legend12->SetBorderSize(0);
  legend12->SetTextSize(0.04);
  legend12->SetTextFont(132);
  legend12->SetLineWidth(1);
  legend12->AddEntry(Zll1Met_DA_Y   , "Data metY 1-jet", "L");
  legend12->AddEntry(Zll1Met_MC_Y   , "MC uncorrected", "L");
  legend12->AddEntry(Zll1Met_CorMC_Y, "MC corrected", "L");
  Zll1Met_MC_Y->SetMaximum(Zll1Met_MC_Y->GetMaximum() * 1.2);
  Zll1Met_MC_Y->SetLineColor(kRed);
  Zll1Met_MC_Y->SetLineWidth(2);
  Zll1Met_MC_Y->Draw("hist");
  Zll1Met_DA_Y->SetLineColor(kBlue);
  Zll1Met_DA_Y->SetLineWidth(2);
  Zll1Met_DA_Y->Draw("e,same");
  Zll1Met_CorMC_Y->SetLineColor(kBlack);
  Zll1Met_CorMC_Y->SetLineWidth(2);
  Zll1Met_CorMC_Y->Draw("same,hist");
  legend12->Draw();
  cv1->cd(3);
  TLegend *legend13 = new TLegend(0.3,0.8,0.9,0.9);
  legend13->SetFillStyle(0);
  legend13->SetFillColor(kWhite);
  legend13->SetBorderSize(0);
  legend13->SetTextSize(0.04);
  legend13->SetTextFont(132);
  legend13->SetLineWidth(1);
  legend13->AddEntry(Zll1TrackMet_DA_X   , "Data TrackMetX 1-jet", "L");
  legend13->AddEntry(Zll1TrackMet_MC_X   , "MC uncorrected", "L");
  legend13->AddEntry(Zll1TrackMet_CorMC_X, "MC corrected", "L");
  Zll1TrackMet_MC_X->SetMaximum(Zll1TrackMet_MC_X->GetMaximum() * 1.2);
  Zll1TrackMet_MC_X->SetLineColor(kRed);
  Zll1TrackMet_MC_X->SetLineWidth(2);
  Zll1TrackMet_MC_X->Draw("hist");
  Zll1TrackMet_DA_X->SetLineColor(kBlue);
  Zll1TrackMet_DA_X->SetLineWidth(2);
  Zll1TrackMet_DA_X->Draw("e,same");
  Zll1TrackMet_CorMC_X->SetLineColor(kBlack);
  Zll1TrackMet_CorMC_X->SetLineWidth(2);
  Zll1TrackMet_CorMC_X->Draw("same,hist");
  legend13->Draw();
  cv1->cd(4);
  TLegend *legend14 = new TLegend(0.3,0.8,0.9,0.9);
  legend14->SetFillStyle(0);
  legend14->SetFillColor(kWhite);
  legend14->SetBorderSize(0);
  legend14->SetTextSize(0.04);
  legend14->SetTextFont(132);
  legend14->SetLineWidth(1);
  legend14->AddEntry(Zll1TrackMet_DA_Y   , "Data TrackMetY 1-jet", "L");
  legend14->AddEntry(Zll1TrackMet_MC_Y   , "MC uncorrected", "L");
  legend14->AddEntry(Zll1TrackMet_CorMC_Y, "MC corrected", "L");
  Zll1TrackMet_MC_Y->SetMaximum(Zll1TrackMet_MC_Y->GetMaximum() * 1.2);
  Zll1TrackMet_MC_Y->SetLineColor(kRed);
  Zll1TrackMet_MC_Y->SetLineWidth(2);
  Zll1TrackMet_MC_Y->Draw("hist");
  Zll1TrackMet_DA_Y->SetLineColor(kBlue);
  Zll1TrackMet_DA_Y->SetLineWidth(2);
  Zll1TrackMet_DA_Y->Draw("e,same");
  Zll1TrackMet_CorMC_Y->SetLineColor(kBlack);
  Zll1TrackMet_CorMC_Y->SetLineWidth(2);
  Zll1TrackMet_CorMC_Y->Draw("same,hist");
  legend14->Draw();
  cv1->SaveAs("test1_met_zll.pdf");

  TCanvas *cv2 = new TCanvas("cv2", "cv2", 1000, 1000);
  cv2->Divide(2,2);
  cv2->cd(1);
  TLegend *legend21 = new TLegend(0.3,0.8,0.9,0.9);
  legend21->SetFillStyle(0);
  legend21->SetFillColor(kWhite);
  legend21->SetBorderSize(0);
  legend21->SetTextSize(0.04);
  legend21->SetTextFont(132);
  legend21->SetLineWidth(1);
  legend21->AddEntry(Zll2Met_DA_X   , "Data metX 2-jet", "L");
  legend21->AddEntry(Zll2Met_MC_X   , "MC uncorrected", "L");
  legend21->AddEntry(Zll2Met_CorMC_X, "MC corrected", "L");
  Zll2Met_MC_X->SetMaximum(Zll2Met_MC_X->GetMaximum() * 1.2);
  Zll2Met_MC_X->SetLineColor(kRed);
  Zll2Met_MC_X->SetLineWidth(2);
  Zll2Met_MC_X->Draw("hist");
  Zll2Met_DA_X->SetLineColor(kBlue);
  Zll2Met_DA_X->SetLineWidth(2);
  Zll2Met_DA_X->Draw("e,same");
  Zll2Met_CorMC_X->SetLineColor(kBlack);
  Zll2Met_CorMC_X->SetLineWidth(2);
  Zll2Met_CorMC_X->Draw("same,hist");
  legend21->Draw();
  cv2->cd(2);
  TLegend *legend22 = new TLegend(0.3,0.8,0.9,0.9);
  legend22->SetFillStyle(0);
  legend22->SetFillColor(kWhite);
  legend22->SetBorderSize(0);
  legend22->SetTextSize(0.04);
  legend22->SetTextFont(132);
  legend22->SetLineWidth(1);
  legend22->AddEntry(Zll2Met_DA_Y   , "Data metY 2-jet", "L");
  legend22->AddEntry(Zll2Met_MC_Y   , "MC uncorrected", "L");
  legend22->AddEntry(Zll2Met_CorMC_Y, "MC corrected", "L");
  Zll2Met_MC_Y->SetMaximum(Zll2Met_MC_Y->GetMaximum() * 1.2);
  Zll2Met_MC_Y->SetLineColor(kRed);
  Zll2Met_MC_Y->SetLineWidth(2);
  Zll2Met_MC_Y->Draw("hist");
  Zll2Met_DA_Y->SetLineColor(kBlue);
  Zll2Met_DA_Y->SetLineWidth(2);
  Zll2Met_DA_Y->Draw("e,same");
  Zll2Met_CorMC_Y->SetLineColor(kBlack);
  Zll2Met_CorMC_Y->SetLineWidth(2);
  Zll2Met_CorMC_Y->Draw("same,hist");
  legend22->Draw();
  cv2->cd(3);
  TLegend *legend23 = new TLegend(0.3,0.8,0.9,0.9);
  legend23->SetFillStyle(0);
  legend23->SetFillColor(kWhite);
  legend23->SetBorderSize(0);
  legend23->SetTextSize(0.04);
  legend23->SetTextFont(132);
  legend23->SetLineWidth(1);
  legend23->AddEntry(Zll2TrackMet_DA_X   , "Data TrackMetX 2-jet", "L");
  legend23->AddEntry(Zll2TrackMet_MC_X   , "MC uncorrected", "L");
  legend23->AddEntry(Zll2TrackMet_CorMC_X, "MC corrected", "L");
  Zll2TrackMet_MC_X->SetMaximum(Zll2TrackMet_MC_X->GetMaximum() * 1.2);
  Zll2TrackMet_MC_X->SetLineColor(kRed);
  Zll2TrackMet_MC_X->SetLineWidth(2);
  Zll2TrackMet_MC_X->Draw("hist");
  Zll2TrackMet_DA_X->SetLineColor(kBlue);
  Zll2TrackMet_DA_X->SetLineWidth(2);
  Zll2TrackMet_DA_X->Draw("e,same");
  Zll2TrackMet_CorMC_X->SetLineColor(kBlack);
  Zll2TrackMet_CorMC_X->SetLineWidth(2);
  Zll2TrackMet_CorMC_X->Draw("same,hist");
  legend23->Draw();
  cv2->cd(4);
  TLegend *legend24 = new TLegend(0.3,0.8,0.9,0.9);
  legend24->SetFillStyle(0);
  legend24->SetFillColor(kWhite);
  legend24->SetBorderSize(0);
  legend24->SetTextSize(0.04);
  legend24->SetTextFont(132);
  legend24->SetLineWidth(1);
  legend24->AddEntry(Zll2TrackMet_DA_Y   , "Data TrackMetY 2-jet", "L");
  legend24->AddEntry(Zll2TrackMet_MC_Y   , "MC uncorrected", "L");
  legend24->AddEntry(Zll2TrackMet_CorMC_Y, "MC corrected", "L");
  Zll2TrackMet_MC_Y->SetMaximum(Zll2TrackMet_MC_Y->GetMaximum() * 1.2);
  Zll2TrackMet_MC_Y->SetLineColor(kRed);
  Zll2TrackMet_MC_Y->SetLineWidth(2);
  Zll2TrackMet_MC_Y->Draw("hist");
  Zll2TrackMet_DA_Y->SetLineColor(kBlue);
  Zll2TrackMet_DA_Y->SetLineWidth(2);
  Zll2TrackMet_DA_Y->Draw("e,same");
  Zll2TrackMet_CorMC_Y->SetLineColor(kBlack);
  Zll2TrackMet_CorMC_Y->SetLineWidth(2);
  Zll2TrackMet_CorMC_Y->Draw("same,hist");
  legend24->Draw();
  cv2->SaveAs("test2_met_zll.pdf");

}
