#!/bin/bash
./merge.sh ./ data data/
./merge.sh ./ ggww data/
./merge.sh ./ qqww data/
./merge.sh ./ ttbar data/
./merge.sh ./ tw data/
./merge.sh ./ dyee data/
./merge.sh ./ dymm data/
./merge.sh ./ dytt data/
./merge.sh ./ wz data/
./merge.sh ./ zz data/
./merge.sh ./ wjets data/
./merge.sh ./ wjets_data data/
./merge.sh ./ wjets_PassFail data/
./merge.sh ./ wgamma data/
./merge.sh ./ hww115 data/
./merge.sh ./ hww120 data/
./merge.sh ./ hww130 data/
./merge.sh ./ hww140 data/
./merge.sh ./ hww150 data/
./merge.sh ./ hww160 data/
./merge.sh ./ hww170 data/
./merge.sh ./ hww180 data/
./merge.sh ./ hww190 data/
./merge.sh ./ hww200 data/
./merge.sh ./ hww250 data/
./merge.sh ./ hww300 data/
